export const USER_ROLE = {
  ADMIN: 'ADMIN',
  STUDENT_AFFAIRS_OFFICE: 'STUDENT_AFFAIRS_OFFICE',
  EVENT_ORGANIZER: 'EVENT_ORGANIZER'
}

export const TIMEOUT = {
  TOAST_SHORT: 3000
}

export const DATE_TIME_FORMATS = {
  ISO: 'YYYY-MM-DDTHH:mm:ss.SSS',
  DATE: 'YYYY-MM-DD',
  TIME: 'HH:mm:ss',
  DATE_TIME: 'YYYY-MM-DD HH:mm:ss',
  DATE_TIME_COMMON: 'DD/MM/YYYY HH:mm'
}
